DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "items" CASCADE;
DROP TABLE IF EXISTS "users_items" CASCADE;

CREATE TABLE IF NOT EXISTS "users"
(
    "id"    integer GENERATED ALWAYS AS IDENTITY UNIQUE PRIMARY KEY,
    "name"  varchar(255),
    "email" varchar(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS "items"
(
    "id"          integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "name"        varchar(255),
    "description" varchar(1500),
    "available"   boolean,
    "owner"       integer
);

CREATE TABLE IF NOT EXISTS "users_items"
(
    "user_id" integer,
    "item_id" integer,

    CONSTRAINT film_genres_key PRIMARY KEY ("user_id", "item_id")
);

ALTER TABLE "items"
    ADD FOREIGN KEY ("owner") REFERENCES "users" ("id");

ALTER TABLE "users_items"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_items"
    ADD FOREIGN KEY ("item_id") REFERENCES "items" ("id");